server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment

  #consul注册
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}






