server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        #server-addr: 192.168.247.128:1111  #集群配置

management:
  endpoints:
    web:
      exposure:
        include: '*'