server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

  #consul注册
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}






